#!/bin/sh
cd ~
# user preferred settings

#cursor size and theme
export XCURSOR_SIZE=24
export XCURSOR_THEME=Adwaita

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/micro

#browser
export BROWSER=firedragon
#terminal
export TERM=xterm-256color
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart 
